### ISSUE TITLE
Dragging doesn't allow dropping in some cases

### ISSUE THREAD

**Issue by Enngage** [haltu/muuri#187] opened 2018-07-13 14:20 UTC
Hi, first - thanks for the awesome library!

I've been using this library to create user dashboards (responsive widths + variable heights of items) and have been experience one particular isuse where I cannot drop item even though there clearly is enough space. Usually, this can be solved by moving items around a bit, but UX suffers.

This can actually be seen in the demo page you have:

![a](https://user-images.githubusercontent.com/7137351/42696262-faea980e-86b7-11e8-9392-b665a038f5cc.gif)

Do you have any idea how this can be improved / fixed? 

I've tried several configurations, but nothing seems to help. This my current config:

```
           layout: {
                fillGaps: false,
                rounding: false,
            },
            dragSortPredicate: {
                threshold: 25,
                action: 'move'
            },
            dragEnabled: true,
            dragSortInterval: 25,
            dragReleaseDuration: 200,
            dragStartPredicate: {
                handle: '.' + this.draggableItemClass
            }
```

Thank you!

**Comment by niklasramo** [comment] 2018-09-20 20:02
Closing as duplicate of #26

**Closed by niklasramo** 2018-09-20 20:02 UTC
Labels: question :thinking:
