### ISSUE TITLE
dragEnabled not working

### ISSUE THREAD

**Issue by angelokal** [haltu/muuri#142] opened 2018-01-29 17:50 UTC
when I use dragEnabled: true, the other items disappear and it not working. why?

**Comment by niklasramo** [comment] 2018-01-30 12:52
Please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/).

**Comment by niklasramo** [comment] 2018-02-27 18:35
Closing this since I cannot reproduce this and no reduced test case is provided.

**Closed by niklasramo** 2018-02-27 18:35 UTC
Labels: question
