### ISSUE TITLE
iOS: click events are not firing on grid items

### ISSUE THREAD

**Issue by robert-j** [haltu/muuri#324] opened 2019-08-27 11:27 UTC
Starting with 0.8.0, click events of elements inside grid items are not firing any longer:

See [https://jsfiddle.net/325dxsbf/2/](https://jsfiddle.net/325dxsbf/2/).

Browser: Safari iOS Safari
Version: iOS 12.4

**Comment by niklasramo** [comment] 2019-08-28 07:07
@robert-j Thanks! I will investigate.

**Comment by gaurav-verma-maropost** [comment] 2019-11-29 07:16
I ran into the similar issue. Is there any update on this ?

**Comment by robert-j** [comment] 2020-01-07 12:56
It seems to be an iOS 12 issue. It works with iOS >= 13.

**Comment by niklasramo** [comment] 2020-03-27 05:52
@robert-j I think this is causing it: https://github.com/haltu/muuri/blob/master/src/Dragger/Dragger.js#L506. However, I don't know any way around it. We need to prevent the default action on "touchstart" event for browsers that don't support requested touch-action property. Let me know if you have some ideas for this.

**Comment by niklasramo** [comment] 2020-06-15 18:15
Closing this as the issue is something that can't be fixed at the moment, at least to my knowledge.

**Closed by niklasramo** 2020-06-15 18:15 UTC
Labels: question
