### ISSUE TITLE
element.animate is not a function: Safari bug.

### ISSUE THREAD

**Issue by onecompileman** [haltu/muuri#136] opened 2018-01-19 02:08 UTC
When I try to drag an Element this error shows up only in Safari.

![image](https://user-images.githubusercontent.com/17823491/35131348-9916410a-fd00-11e7-961a-b3136e06c33c.png)

**Comment by niklasramo** [comment] 2018-01-19 06:31
Have you included the [Web Animations polyfill](https://github.com/web-animations/web-animations-js) in the site? Safari does not support Web Animations yet, so it needs the polyfill. It's also mentioned in [Muuri's readme](https://github.com/haltu/muuri#2-get-the-dependencies).

**Comment by niklasramo** [comment] 2018-02-27 18:40
Closing this since I cannot reproduce this and no reduced test case is provided.

**Closed by niklasramo** 2018-02-27 18:40 UTC
Labels: question
