### ISSUE TITLE
Not scrolling automatically grid

### ISSUE THREAD

**Issue by RamcharanG** [haltu/muuri#231] opened 2018-11-30 09:59 UTC
I have a use case where I want to scroll the grid automatically when user tries to drag the child item down.Let's say user wants to put the first child item to 30th position.It is difficult to drop the first item to 30th position at one go.If the plug-in supports the grid to automatically scroll user may find it easy to drop wherever he/she likes to drop.Is it achievable to scroll automatically the grid ??

**Comment by niklasramo** [comment] 2018-11-30 11:18
Duplicate of https://github.com/haltu/muuri/issues/9

And yes, it is achievable, just not implemented yet.

**Comment by RamcharanG** [comment] 2018-11-30 11:31
When are you planning to implement this ??

**Closed** 2018-12-08 06:35 UTC
Labels: duplicate :v:
