### ISSUE TITLE
Horizontal Kanban?

### ISSUE THREAD

**Issue by mspanish** [haltu/muuri#120] opened 2017-12-04 15:48 UTC
Thanks for the awesome grid script! I am using both types of grids to display letters in an [alphabet learning app]( https://smartydecks.com/#grid) - (just a work in progress) - and one thing that may be unusual that I'm trying to do is drag and drop from a series of vertical Kanban layouts of the letter groups, to a horizontal word board above. I tried adding it as a Kanban but I couldn't get the CSS right to make it go horizontal.  So actually that would probably work better, to just have a horizontal layout for the Kanban instead - is that possible?

**Comment by niklasramo** [comment] 2017-12-07 16:12
Hi @mspanish! That looks like an awesome project working on 👍 I'm not exactly sure I understand what you are trying to achieve, but here's the simplest demo I could build to demonstrate how a basic horizontal grid is set up with Muuri: https://codepen.io/niklasramo/pen/xPoVPe

**Comment by mspanish** [comment] 2017-12-07 17:20
Thanks a lot! @niklasramo  - still much work in progress, that's for sure! The regular grids work great and the user can drag above to the "word grid"  - as it's part of the array of grids. But for the Kanban one, I'm not sure how to either set up one grid that goes horizontal, while the others in the grid array need to stay vertical. Either that or use 1 regular grid and then all the others Kanban. I'll attach a screen of the separate grids I have now - which aren't in the same array of grids so they aren't talking to each other. 

![grid](https://user-images.githubusercontent.com/206150/33728630-7d6a83f8-db27-11e7-9006-5e97936f0db1.PNG)

**Comment by niklasramo** [comment] 2017-12-07 21:33
Hmmm.. so you want to drag stuff from the grids in the kanban layout to the horizontal grid above them. And your the problem is getting the horizontal grid laid out correctly, right? Technically this should be all doable pretty easily. If you could create a reduced test case of this scenario in codepen/jsfiddle I could maybe help you out better. I have a feeling this is more CSS/styling related issue than Muuri related issue though.

**Comment by mspanish** [comment] 2017-12-07 22:04
yup definitely - I hate CSS, only do it because I have to :)  I'll work on that!

**Comment by mspanish** [comment] 2017-12-08 22:06
Is there a way to get the id or class of the grid an item is being dragged from?

**Comment by niklasramo** [comment] 2017-12-08 22:49
You can always access any grid item's dom element using `item.getElement()`. From there on you can use the [Element API](https://developer.mozilla.org/en-US/docs/Web/API/Element).

**Comment by mspanish** [comment] 2017-12-08 22:50
@niklasramo  yes great thanks but how about the grid itself?

**Comment by niklasramo** [comment] 2017-12-08 23:11
A grid instance has the same method: `grid.getElement()`.

**Comment by mspanish** [comment] 2017-12-08 23:12
Ah super thanks

**Comment by niklasramo** [comment] 2017-12-08 23:13
I know the docs are scarily big, but well worth a read if you're building something with Muuri.

**Comment by mspanish** [comment] 2017-12-08 23:15
Yes for sure, I appreciate your thoroughness!

**Comment by sskanthi** [comment] 2017-12-23 16:57
Hi @niklasramo, I am trying to build a horizontal Kanban board using Muuri. First of all thanks, its so smooth. But I am facing a hurdle, the screen doesn't scroll whenever I am trying to drag an item to a grid which is not visible in the view port. Is there any option in built in Muuri to get this to work?

**Comment by niklasramo** [comment] 2017-12-23 22:15
@sskanthi Currently there's no built-in solution for that, but it is planned: https://github.com/haltu/muuri/issues/9.

**Comment by sskanthi** [comment] 2017-12-24 16:28
Thanks @niklasramo.

**Comment by niklasramo** [comment] 2018-01-19 06:49
This issue seems resolved -> closing.

**Closed by niklasramo** 2018-01-19 06:49 UTC
Labels: question
