### ISSUE TITLE
fillGaps property does not seem to work

### ISSUE THREAD

**Issue by joeSaad** [haltu/muuri#264] opened 2019-03-14 22:12 UTC
I am placing the items in the dom, the fillGaps by default which is `false`, will let the items be presented as in the dom. However, this is not the case. Attached is a screenshot, showing item 9 proceeding 7 and 8. Why is item 7 in the middle and not in the left? 
![127 0 0 1_5500_index html (2)](https://user-images.githubusercontent.com/1170032/54395107-d0886700-467c-11e9-9689-5e66d8538c59.png)

**Comment by lokeshkanagala** [comment] 2019-03-14 22:21
Yes. This is one of the issue I faced as well. Any help would be appreciable.

**Comment by niklasramo** [comment] 2019-03-14 22:36
This is how the default algorithm works (by design), it's not a bug. There are actually no columns in Muuri (although it may seem like it), the layout algorithm (default config) traverses from left to right and if it does not find suitabble slot in that row it moves to the next row. There are no definable rows either, they are dynamically calculated based on items.

You can always create your own layout algorithm, which I encourage you to do. Muuri's defaults can't please everyone, which is why it is heavily customizable to suit one's needs.

**Comment by mbracker** [comment] 2019-03-14 22:38
@niklasramo how is the default algorithm different from `fillGaps = true`? Or maybe it's not?

**Comment by niklasramo** [comment] 2019-03-14 22:41
When fillGaps is enabled the item will be placed on the first free slot in the grid. Otherwise it will be placed on the first free slot after the previous item. You can see the difference on Muuri's website grid demo.

**Comment by mbracker** [comment] 2019-03-14 22:44
Got it. So in this example, item 7 is placed in the middle because items (1 + 4) are taller than items (2 + 5). If `fillGaps` is enabled, would you expect item 7 to be placed where item 9 is, or is the "first free slot" still below item 5?

**Comment by niklasramo** [comment] 2019-03-14 22:46
Yes. And in this example I wouldn't expect fillGaps to have any effect.

**Comment by mbracker** [comment] 2019-03-14 22:47
👍 thanks for the clarification!

**Comment by niklasramo** [comment] 2019-03-15 09:29
I'll close this one since there is no real issue here.

**Closed by niklasramo** 2019-03-15 09:29 UTC
Labels: question

**Comment by joeSaad** [comment] 2019-03-15 15:21
Thanks the explaining
