### ISSUE TITLE
building grid blocks browser

### ISSUE THREAD

**Issue by papakai** [haltu/muuri#296] opened 2019-07-09 08:03 UTC
Hi there,

many many thanks for your hard work on this library, I am really enjoying it - it is perfect for our purpose!

The only issue that is left, is that in case you have large lists with nested lists (items can be dragged'n'dropped in between), the browser is blocking while muuri is generating the dom. I think rewriting muuri to use web workers, could solve that issue. e.g. I want to show a loading icon and then generating the dom. even though the line for showing the icon in dom appears before starting with muuri, the browser already starts blocking.

![image](https://user-images.githubusercontent.com/229425/60870522-55514f00-a231-11e9-918f-7fcc94c28430.png)

The calculation load of muuri needs to be put into web workers as far as possible to avoid this.
I hope you can follow my thoughts. :)

Cheers
Kai

**Comment by niklasramo** [comment] 2019-07-10 21:31
@papakai yep, I actually thought about using WebWorkers from the very beginning for the layout algorithm since I thought it would indeed get really heavy in some scenarios. And making it happen is not actually _that_ difficult, one just needs to make the layout procedure async and that's pretty much the gist of it API wise.

However, after testing the layout countless times I haven't been able to push it to a point it would actually block the DOM. Which is also why I never went about doing the async layout API change. However, when you go past 200 items and start drag n' dropping iyou might very well see jankyness on some browsers (Firefox for example), which is caused mostly by layout thrashing. That's something I'm actually trying to make smoother in the upcoming new version.

But out of curiosity... how many items are we talking about here? I've only tested Muuri with about 1000 items, which I think is already way more than needed for your usual scenario.

**Comment by papakai** [comment] 2019-07-12 14:47
@niklasramo I am talking about a sum of 1689 TLDs. They are splitted in several categories.A TLD itself can be part of multiple categories, can be moved by drag'n'drop to another category, duplicates are removed. I also have made an exception: a category where drag'n'drop is not allowed to. Categories are a muuri list and the TLDs again a nested list in each category.

Thanks for pointing to FF, will check how well he is doing this scenario.

**Comment by papakai** [comment] 2019-07-12 15:31
FF looks good, matches the performance of chrome in my scenario. I have not detected any issue with FF so far. I am using the latest FF and chrome release.

**Comment by niklasramo** [comment] 2019-07-15 11:57
Whoah, that's a lot of items 🙂 In any case, I'm not sure if the layout calculation is the bottleneck there, it could also be something else. The layout calculation is the part which is somewhat straightforward to do in a WebWorker if we make the layout API async, but the rest of the calculations are not so straightforward (and also should not have a big impact). Can you confirm somehow that it really is the layout calculation that is the cause of the slowdown?

e.g. Replace this https://github.com/haltu/muuri/blob/master/src/Grid/Grid.js#L531 with this:
````
var t = performance.now();
var layout = this._updateLayout();
console.log(performance.now() -t);
``

**Comment by niklasramo** [comment] 2019-07-15 12:01
Also, alternatively, you could try to create a simpler layout algorithm as your layout does not look (based on the pics) to be needing such complex calculations as what the default layout algorithm does. I think you could speed up the layout process quite a lot with that actually.

**Comment by papakai** [comment] 2019-07-15 12:34
Thanks @niklasramo I'll come back to you/this issue in about month I think :-)
Before applying the above code change, I am interested in switching to v0.8.0 1st (thanks a lot for that release!) and this week I will be busy enough to get things finished. Finally, I will also be able to provide you a demo access to that module, so that you also have a playground for something with such many items. This was my 1st muuri project and of course it could be that I did not everything in the way of best practices ;-)

I'll keep you posted. Again thanks.

**Comment by niklasramo** [comment] 2020-06-15 18:39
Muuri v0.9.0 was released with a lot of performance improvements as well as adding support for layout calculations in web workers. I suggest trying that now 🙂

**Closed by niklasramo** 2020-06-15 18:39 UTC
Labels: question
