### ISSUE TITLE
The website behaves strange in 58.0.3029.110 (64-bit) .

### ISSUE THREAD

**Issue by SidKwok** [haltu/muuri#54] opened 2017-06-04 13:18 UTC
<img width="484" alt="bb9d6aff-3ccb-4641-823a-698b0e07977a" src="https://cloud.githubusercontent.com/assets/13268747/26761943/57bfdd36-496b-11e7-96eb-a11a9258c7cb.png">

chrome and mac

**Comment by niklasramo** [comment] 2017-06-04 18:06
Thanks for reporting, will check that out.

**Comment by niklasramo** [comment] 2017-06-04 19:00
Should be fixed now, at least theoretically. I don't have a mac to test this on, but I figured this bug is probably caused by this issue: https://stackoverflow.com/questions/22681141/select-option-padding-not-working-in-chrome.

**Comment by niklasramo** [comment] 2017-06-05 07:29
Oops, that last fix caused double select arrows in IE. Fixed now for IE10 and IE11. The demo site is built for IE10+ although Muuri does support IE9 (gotta fix that also sometime).

**Comment by niklasramo** [comment] 2017-06-05 10:07
Can someone confirm that the website is working properly now on mac with chrome?

**Comment by SidKwok** [comment] 2017-06-05 14:17
@niklasramo It was fixed on mac with chrome.

**Closed** 2017-06-05 18:20 UTC
